apiVersion: v2
kubeVersion: '>=1.23.0-0'
name: seerr-chart
description: Seerr helm chart for Kubernetes
type: application
version: 3.0.1
# renovate: image=ghcr.io/seerr-team/seerr
appVersion: '3.0.1'
maintainers:
  - name: Seerr Team
    url: https://github.com/orgs/seerr-team/people
sources:
  - https://github.com/seerr-team/seerr/tree/main/charts/seerr
home: https://github.com/seerr-team/seerr
