blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Support via Discord
    url: https://discord.gg/seerr
    about: Chat with other users and the Seerr dev team
  - name: ðŸ’¬ Support via GitHub Discussions
    url: https://github.com/seerr-team/seerr/discussions
    about: Ask questions and discuss with other community members
